name: CLA

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.CLA_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_TOKEN }}
        with:
          path-to-signatures: "signatures.json"
          path-to-document: "https://github.com/William-Harrison/cla/blob/main/cla.md"
          branch: "main"
          allowlist: WDH-Bot
          signed-commit-message: "@$contributorName has signed the CLA"
          create-file-commit-message: "Generate CLA Signatures File"
          custom-allsigned-prcomment: "All contributors have signed the CLA."
          remote-organization-name: "William-Harrison"
          remote-repository-name: "cla"
