name: Closed PR

on:
  pull_request_target:
    types:
      - closed

jobs:
  merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            ## You're nearly done!
            Just follow the steps below and you can start using your domain!

            <a href="https://www.buymeacoffee.com/phenax" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me a Coffee" height="28" width="119"></a> <a href="https://liberapay.com/phenax" target="_blank"><img src="https://img.shields.io/badge/liberapay-donate-yellow.svg?style=for-the-badge" alt="Liberapay"></a>

            ---

            ### Server Owners
            If your domain points to a server you own, add your-domain.is-a.dev to your domain configuration. For HTTPS, you will have to configure an SSL certificate to allow the new subdomain to work ([here's why](https://get.dev/#:~:text=The%20.dev%20top%2Dlevel%20domain%20is%20included%20on%20the%20HSTS%20preload%20list%2C%20making%20HTTPS%20required%20on%20all%20connections%20to%20.dev%20websites%20and%20pages%20without%20needing%20individual%20HSTS%20registration%20or%20configuration.%20Security%20is%20built%20in.)).

            ### GitHub Pages
            - Go to your GitHub repository that you use for your is-a.dev domain
            - Click on the Settings tab
            - Click on the Pages link in the sidebar
            - In the custom domain option, enter the domain you registered.
            - Check the `Enforce HTTPS` checkbox
            - Give your domain some time (~24 hours) for the changes to propagate
            - Enjoy your domain!

            ---

            **Need help with your domain?** If you are having trouble setting up your domain, please [create an issue](https://github.com/is-a-dev/register/issues/new/choose) and we will try and help you as soon as possible!

            **Made a mistake in the records?** Don't worry, you can create a new pull request with the corrections.

  closed:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            ## Your pull request has been closed
            These are some of the reasons of why your pull request might have been closed:

            - Inaccessible website
            - Incomplete website
            - Invalid JSON
            - Invalid records
            - NSFW content
            - Not enough information provided under the "owner" key
            - Suspected abuse
            - Using unsupported services such as Vercel or Netlify

            ### Still want a domain?
            - Please read the [docs](https://is-a.dev/docs) and follow the required format.
            - Make sure your website meets our requirements.
            - Open a new pull request.

            ### Need more support?
            Join our Discord if you need more help and one of our staff members will help you out!

            [![Discord Server](https://discord.com/api/guilds/830872854677422150/widget.png?style=banner3)](https://discord.gg/PZCGHz4RhQ)

            ### Donate

            <a href="https://www.buymeacoffee.com/phenax" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me a Coffee" height="28" width="119"></a> <a href="https://liberapay.com/phenax" target="_blank"><img src="https://img.shields.io/badge/liberapay-donate-yellow.svg?style=for-the-badge" alt="Liberapay"></a>
