name: "PR"

on:
  pull_request_target:
    branches: ["main", "master"]
    types: ["opened", "closed"]

jobs:
  opened:
    if: github.event_name == "pull_request_opened"
    name: "Opened"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Comment"
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ".github/comments/opened.md"

  merged:
    if: github.event.pull_request.merged == true
    name: "Merged"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Comment"
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ".github/comments/merged.md"

  closed:
    if: github.event.pull_request.merged == false
    name: "Closed"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Comment"
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ".github/comments/closed.md"
